name: CI

on:
  schedule:
    - cron: 0 */6 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "ips.csv"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        # Only runs if all of the files exists
        run: |
          rm ips.csv
          
      - name: wget webpage
        run: |
          wget https://config.zscaler.com/zscaler.net/cenr
          
      - name: update python and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install html-to-csv
          
      - name: convert html to csv
        run: |
          html2csv cenr -o ips.csv
          rm cenr
      
      - name: add and commit
        continue-on-error: true
        run: |
          git config --local user.name "donantoniosantos"
          git config --local user.email "donantoniosantos@gmail.com"
          git add ips.csv
          git commit -m 'new zscaler file'
          git push -u origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
